
/*
 * Filename: swc_engine.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_ENGINE
#define _H_DEFINE_SWC_ENGINE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_ENGINE_INCLUDES */

/* USER CODE END SWC_ENGINE_INCLUDES */



/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */


/*
* component: swc_engine
* cycletime: 100
* description: Runnable for running the engine.
* events: 
* name: ENGINE_setEngine_run
* shortname: setEngine
* signalIN: so_speed
* signalOUT: so_engine
* task: tsk_inputoutput
*/
void ENGINE_setEngine_run(RTE_event ev);


#endif