

/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

#include "intToASCII.h"
#include "led.h"
#include "watchdog.h"

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
* component: swc_engine
* cycletime: 100
* description: Runnable for running the engine.
* events: 
* name: ENGINE_setEngine_run
* shortname: setEngine
* signalIN: so_speed
* signalOUT: so_engine
* task: tsk_inputoutput
*/
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */
    
    static RC_t res = RC_SUCCESS;
    static SC_ENGINE_data_t engineValue = SC_ENGINE_INIT_DATA;
    static char asciiConvert[30];
    
    /*
     * Updating the Alive Monitoring register.
     * Bit Position 2 - RUNNABLE_SETENGINE
     **/
    res = WD_Alive(2);
    /**
     * Error Handling
     **/
    if(res != RC_SUCCESS)
    {
        UART_LOG_PutString("Watchdog Status register update failed. \n");   
    }

    /**
     * Engine value is updated by copying the speed value only if the speed value is not too old.
     * Here, the speed value is expected to be not older than 100ms.
     * Otherwise engine value is copied as 0.
     **/
    if(RTE_SC_SPEED_getAge(&SO_SPEED_signal) < 100)
    {
        engineValue.engine = RTE_SC_SPEED_get(&SO_SPEED_signal).speed;
        UART_LOG_PutString("ENGINE UPDATED. \n");
    }
    else
    {
        UART_LOG_PutString("Speed Signal Age too old ie. ");
        intToASCII(RTE_SC_SPEED_getAge(&SO_SPEED_signal), (uint8_t*)&asciiConvert, 4);
        UART_LOG_PutString(asciiConvert);
        UART_LOG_PutString("ms. \n");
        engineValue.engine = 0;
    }
    
    /**
     * Engine value updated.
     **/
    RTE_SC_ENGINE_set(&SO_ENGINE_signal, engineValue);
    
    /**
     * Engine value sent to the hardware.
     **/
    res = RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
    /**
     * Error Handling.
     **/
    if(res != RC_SUCCESS)
    {
        UART_LOG_PutString("Engine value was not written into hardware. \n");
        LED_Set(LED_YELLOW, LED_ON);
    }
    
    /**
     * Engine value is used in PWM of Green channel of RGB LED.
     **/
    LED_RGB_Set(0,engineValue.engine,0);
    
    /**
     * Display Engine value.
     **/
    UART_LOG_PutString("Engine : ");
    intToASCII((uint32_t)RTE_SC_ENGINE_get(&SO_ENGINE_signal).engine, (uint8_t*)&asciiConvert, 4);
    UART_LOG_PutString(asciiConvert);
    UART_LOG_PutString("\n");

    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

