

/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"



/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

#include "intToASCII.h"
#include "led.h"
#include "watchdog.h"

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
* component: swc_brakeLight
* cycletime: 0
* description: Runnable for setting the brake light.
* events: ev_speed_onData
* name: BRAKELIGHT_setBrakeLight_run
* shortname: setBrakeLight
* signalIN: so_speed
* signalOUT: so_brakeLight
* task: tsk_inputoutput
*/
void BRAKELIGHT_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_setBrakeLight_run */
    
    static RC_t res = RC_SUCCESS;
    
    /*
     * Updating the Alive Monitoring register. 
     * Bit Position 3 - RUNNABLE_SETBRAKELIGHT
     **/
    res = WD_Alive(3);
    /**
     * Error Handling
     **/
    if(res != RC_SUCCESS)
    {
        UART_LOG_PutString("Watchdog Status register update failed. \n");   
    }
    
    static SC_BRAKELIGHT_data_t brakelight_st = SC_BRAKELIGHT_INIT_DATA;
    
    /**
     * The brake light 'RED LED' turns on when the speed is 0.
     * Else it remains turned off.
     **/
    if(RTE_SC_SPEED_get(&SO_SPEED_signal).speed == 0)
    {
        brakelight_st.brakeLight = TRUE;
        UART_LOG_PutString("BRAKES ON. \n");
        LED_Set(LED_RED, LED_ON);
    }
    else
    {
        brakelight_st.brakeLight = FALSE;
        UART_LOG_PutString("BRAKES OFF. \n");
        LED_Set(LED_RED, LED_OFF);
    }
    
    /**
     * Brake status updated.
     **/
    RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal,brakelight_st);
    
    /**
     * Brake status sent to the hardware.
     **/
    res = RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);
    /**
     * Error Handling.
     **/
    if(res != RC_SUCCESS)
    {
        UART_LOG_PutString("Brake Status was not written into hardware. \n");
        LED_Set(LED_YELLOW, LED_ON);
    }

    /* USER CODE END BRAKELIGHT_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

