

/*
 * Filename: sc_joystick_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_joystick_type.h"



/* USER CODE START SC_JOYSTICK_INCLUDE */

#include "joystick.h"

/* USER CODE END SC_JOYSTICK_INCLUDE */


/*
* description: Signalclass representing the user input.
* name: sc_joystick
* shortname: joystick
*/

/* USER CODE START SC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SC_JOYSTICK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_JOYSTICK signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_JOYSTICK_driverIn(SC_JOYSTICK_data_t *const data)
{
	/* USER CODE START driverInSC_JOYSTICK */
    
    RC_t res = RC_SUCCESS;
    
	//Read data from the MCAL driver
    
    /**
     * Reading the live joystick values along x and y directions.
     **/
    res = JOYSTICK_ReadPosition(&data->Joystick_X, &data->Joystick_Y);

	return res;
    
	/* USER CODE END driverInSC_JOYSTICK */
}



